workflows:
  ios-workflow:
    name: iOS Build

    environment:
      xcode: latest

      ios_signing:
        distribution_type: app_store
        bundle_identifier: club.the99percent.fitx

    integrations:
      app_store_connect: Codemagic

    scripts:
      - name: Build IPA
        script: |
          xcode-project use-profiles
          xcode-project build-ipa \
            --project "ClubFitX.xcodeproj" \
            --scheme "ClubFitX"

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true