workflows:
  ios-workflow:
    name: iOS Build

    environment:
      xcode: latest

      ios_signing:
        distribution_type: app_store
        bundle_identifier: club.the99percent.fitx

    integrations:
      app_store_connect: Codemagic

    scripts:
      - name: Archive
        script: |
          xcodebuild archive \
            -project "ClubFitX.xcodeproj" \
            -scheme "ClubFitX" \
            -archivePath $CM_BUILD_DIR/ClubFitX.xcarchive \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_STYLE=Automatic \
            DEVELOPMENT_TEAM=KH7T23M958 \
            -allowProvisioningUpdates

      - name: Export IPA
        script: |
          cat > exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
          "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>KH7T23M958</string>
            <key>uploadBitcode</key>
            <false/>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/ClubFitX.xcarchive \
            -exportPath $CM_BUILD_DIR/build/ios/ipa \
            -exportOptionsPlist exportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true